name: Build and Deploy Windows Container App to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-to-dev:
    runs-on: windows-latest
    
    steps:
      
    # Check out the repo to the app service VMs
    - uses: actions/checkout@v1
    
    # Authenticate a Service Principal to continuously deploy to your provisioned app service
    - name: Azure Authentication
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
               
    # Use docker login to log into ACR *********************************
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: jefmartiregistryad.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    # Build and push the image to Azure Container Registry **************
    - name: Build and Push container to ACR
      run: |
        docker build --file=taskapp/taskapp/Dockerfile -t jefmartiregistryad.azurecr.io/dotnetframeworkwc:${{ github.sha }} .
        docker push jefmartiregistryad.azurecr.io/dotnetframeworkwc:${{ github.sha }}  
     #   docker build -t jefmartiregistry.azurecr.io/dotnetframeworkwc:${{ github.sha }} dotnetwindowsapp/dotnetwindowsapp/
           
          
    # Deploy your container to App Service ******************************
    - name: Deploy Container to Azure App Service
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'jefmarti-aspnet-fw-ad'
        images: 'jefmartiregistryad.azurecr.io/dotnetframeworkwc:${{ github.sha }}'
        
    # Deploy a dacpac file to a provisioned SQL server
#    - name: Azure SQL Deploy
#      uses: Azure/sql-action@v1
#      with:
#        server-name: jefmartiserv.database.windows.net
#        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
#        dacpac-package: './data.dacpac'
